---
- name: "Set authorized key"
  tags: authorized_keys
  authorized_key:
    user: "{{ item['user'] }}"
    state: present
    key: "{{ item['key'] }}"
  when: authorized_user_key_list != []
  with_items: "{{ authorized_user_key_list }}"
