---
- hosts: all
  pre_tasks:
    - name: check target is {{ hostname }} or localhost
      fail:
        msg: target is {{ ansible_hostname }}
      when:
        - ansible_hostname != hostname
        - ansible_hostname != "localhost"
      tags: always
    - name: include vars
      include_vars: file=inventory/devops/config/server.yml
      tags: always

- import_playbook: manage-docker.yml
- import_playbook: manage-prometheus.yml
