---
# deploy services
- name: Create Folders
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 777
  loop:
    - "/opt/grafana_data/"
    - "/var/lib/jenkins"

- name: Start docker-compose
  shell: 'docker-compose up -d'